# NOTE: reusing psoc6.cmake docker image
# SW dependencies are the same (CMake, Ninja, GCC, LLVM, ModusToolbox 2.2.1)

resources:
  containers:
  - container: psoc6
    image: vmmedvid/psoc6.cmake:latest

trigger:
- master

pr:
- master

jobs:
- job: linux_gcc
  pool:
    vmImage: 'ubuntu-18.04'
  container: psoc6
  steps:
  - task: Bash@3
    inputs:
      filePath: ci/build-all.sh
      arguments: --toolchain GCC
    env:
      CMAKE_GIT_SHALLOW: ON
      GCC_TOOLCHAIN_PATH: /opt/gcc-arm-none-eabi-10-2020-q4-major
